server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
           uri: https://github.com/bpatel007/common
           search-paths:
             - app*
        repos:
          app1:
            pattern:
              - app1*
            app1: https://github.com/bpatel007/common
            searchPaths:
              - app1*

          app2:
            pattern:
              - app2*
            uri: https://github.com/bpatel007/common
            searchPaths:
              - app2*


management:
  endpoints:
    web:
      exposure:
        include:
        - '*'   
        
        